set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)

set(VCPKG_CMAKE_SYSTEM_VERSION "10.0.17763.0")
set(VCPKG_ENV_PASSTHROUGH CCP_EVE_PERFORCE_BRANCH_PATH)

# set(VCPKG_VISUAL_STUDIO_PATH "$ENV{ProgramFiles\(x86\)}\\Microsoft Visual Studio\\2017\\Professional")

set(VCPKG_BUILD_TYPE release)