set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)

set(VCPKG_CMAKE_SYSTEM_VERSION "10.0.17763.0")

if (PORT MATCHES "gtest")
    set(VCPKG_BUILD_TYPE release)
endif()

set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreadedDLL)
